// USERS
export const NEW_USER_EMAIL = 'NEW_USER_EMAIL'
export const USER_CREATION_EMAIL_FAILED = 'USER_CREATION_EMAIL_FAILED'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
