// USERS
export const NEW_USER_EMAIL = 'NEW_USER_EMAIL'
export const USER_CREATION_EMAIL_FAILED = 'USER_CREATION_EMAIL_FAILED'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

// ALERTS
export const ALERT = 'ALERT'

// NEW LISTINGS
export const UPDATE_NL_TITLE = 'UPDATE_NL_TITLE'
export const UPDATE_NL_PRICE = 'UPDATE_NL_PRICE'
export const UPDATE_NL_DESCRIPTION = 'UPDATE_NL_DESCRIPTION'
export const UPDATE_NL_IMAGES = 'UPDATE_NL_IMAGES'
export const TOGGLE_UPLOADER = 'TOGGLE_UPLOADER'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const UPDATE_GEO = 'UPDATE_GEO'
export const UPDATE_LOCATION = 'UPDATE_LOCATION'

// CHECKOUT
export const ADD_TO_CHECKOUT = 'ADD_TO_CHECKOUT'
export const READ_CHECKOUT_DATA = 'READ_CHECKOUT_DATA'
export const ERROR_READ_CHECKOUT_DATA = 'ERROR_READ_CHECKOUT_DATA'

// UPLOADS
export const UPDATE_UPLOAD_PROGRESS = 'UPDATE_UPLOAD_PROGRESS'
export const NUMBER_IMAGES_COMPLETE = 'NUMBER_IMAGES_COMPLETE'
export const TOTAL_IMAGES = 'TOTAL_IMAGES'
