const charge = { id: 'ch_18llw4HURi2ecRp71I7LLRI3',
  object: 'charge',
  amount: 400,
  amount_refunded: 0,
  application_fee: null,
  balance_transaction: 'txn_18llw4HURi2ecRp7bOLv8TP2',
  captured: true,
  created: 1471985752,
  currency: 'gbp',
  customer: null,
  description: null,
  destination: null,
  dispute: null,
  failure_code: null,
  failure_message: null,
  fraud_details: {},
  invoice: null,
  livemode: false,
  metadata: {},
  order: null,
  paid: true,
  receipt_email: null,
  receipt_number: null,
  refunded: false,
  refunds:
   { object: 'list',
     data: [],
     has_more: false,
     total_count: 0,
     url: '/v1/charges/ch_18llw4HURi2ecRp71I7LLRI3/refunds' },
  shipping: null,
  source:
   { id: 'card_18llvzHURi2ecRp7Qd4DD2Mh',
     object: 'card',
     address_city: null,
     address_country: null,
     address_line1: null,
     address_line1_check: null,
     address_line2: null,
     address_state: null,
     address_zip: 'TR36FD',
     address_zip_check: 'pass',
     brand: 'Visa',
     country: 'US',
     customer: null,
     cvc_check: 'pass',
     dynamic_last4: null,
     exp_month: 5,
     exp_year: 2019,
     fingerprint: 'bgR3uJyNABFiGDAY',
     funding: 'credit',
     last4: '4242',
     metadata: {},
     name: 'jamie@tradeitcornwall.co.uk',
     tokenization_method: null },
  source_transfer: null,
  statement_descriptor: null,
  status: 'succeeded' }

export default charge
